version: '3'
services:
  mariadb_db:
    container_name: mariadb_container
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    image: "mariadb:latest" 
    restart: always
    volumes:
      - "mariadb_data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3333:80"
    environment:
      - PMA_HOST=mariadb_db
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - mariadb_db

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - WORDPRESS_DB_HOST=mariadb_db
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=secret
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb_db
    volumes:
      - wordpress:/var/www/html

volumes:
  mariadb_data: {}
  wordpress: {}
