version: '3' 

services:

  mariadb_db:
    container_name: mariadb_container
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: wordpress_user
      MARIADB_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin
    restart: always
    ports:
      - "3333:80"
    enviroment: 
      PMA_HOST: mariadb_db
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - wordpress:/var/www/html/phpmyadmin

  wordpress:
    container_name: wordpress_container
    depends_on: 
      - mariadb_db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    enviroment:
      WORDPRESS_DB_HOST: mariadb_db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress_db 
    volumes:
      - wordpress:/var/www/html

  volumes:
    wordpress: ./wordpress/
    mariadb: ./mariadb/